# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  packagemanager:  # id of input
    description: 'Package Manager'
    required: true
    default: 'npm'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who-to-greet }}
